branches:
  only:
  - master
language: python
addons:
    apt:
        packages:
            - optipng
env:
  global:
  # wradlib.github.io
  - secure: "hBgHz6TnoInPUmPFesrx15GyVinW4qeXRhHj//s7ep7Dlht35qEIpZubX+cNxhHG7VlGxBg+qV7byEe5qFXQEn4yA4lBUAxxHnk4mo3QtEhKsMvZwJWstRT7Vqfygjg5smaaqL1AZO7dMj8Wf5HXRSBRohBBrewJAZhkVwihUU8YWs110kYAxWvEUpDMS8pkXxqVW5qVaYMG+ZiXl8t/+JHA0jy/VcMSLf66GIDRHBpp9KzDO5ui11jua/q7pHVKzcPMUO6hWFpvhhdW0rMd49WtBrx/+FVJKhTae0k22w3CBNU1Sv472we6WH8vv8X6FSFS8v8dQQR9R638h18aGlWf2JAgB5oTjwgJF6Vk0G19o70yHTPgUtaTgPxkS+x5xVnPIFpB+2/z6fbUCce3HfVylLVHoWXuo4Pqk5BM20meK8QGIBFiua8DG3PpXAV2HyUjPanFsLNfSLhvynBTMLbNHpcgm08h7b3TE2agvWw6uJ8th+DQeEndsaRfrwoaVP/aZrQktkgXVdo6JQMa6jNCfA8S93q/rYimdJUnI0atjO3Rsuv2EI0FhNt4Jo+9fGLMheUivumjkf/qbS4L0m0x6Pcm4h+tnBEduprrXdxP3/tvf28XfNQ+GtRzXQEoHT3xyEC+DJSjblls3Drjj+qIIj7L2DY+jf8LqwevpzM="
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always

before_install:
  - git submodule update --init --recursive
after_success: make github 

