branches:
  only:
  - master
language: python
addons:
    apt:
        packages:
            - optipng
env:
  global:
  - secure: "IW4eKCuJOW0ydbPcx8A2Y0VIQnc6cznCmjQiu+J7Je2ReK8bidTWoRlWawvdWADxG11Bwh6BZhthIf9UstsWZREwbMfDWrcrBSyNEHRw72wsXgdn8XT3mSoUZXIuzfoqwPFxgTlO+VshumdjI5mEkcxR+jbNoPqdhzFIpxZmqkmaw0zwv48Yz5n5sg0e52ZwGNalKvxY6bgzcDibGPMCc7bQdxqzsTdeM9TbXDWYGi+eU2hmI03WU9Fe8iLmgihU/WLafiK4sBgHphxZlwnTeSTkzLtJmEosT4aQiQ/z/B4p17abMLrnc6hv2ySo0bN9idm9MpMzUJnYe4VyGqdUL1PCAjZnv9QurCOOQpZ9yxTjTI3teKiU0qjvyg8B4tMnHYSMEkN8s1O2zic/ajctTliwZG97BJjO2CfSR5yTv6PBsJfW23rrLzO8SRrzVO+evkn9T/HbIxMxQHC8F0XN1IrfPdZ5VIkSnJVVkuERkDYDDLUPzCRGQtRIo+NWVFvg5rMoMsb+GA/lMrtvp47jLR3YVNnKwMpQlRrVOtz22G/0KVPwpdRA63TP1YjaBjF6q96jJ9V7wJ0ZdmAWllHmTBnYmDLpZw8AvotK0Y0dzXvZlhHykN+G8XciWLkAuGUYYYPNUBqtnFuFCuW0NbrY7WqFANShQ5kZ3wdwnOxtx4M="
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always

before_install:
  - git submodule update --init --recursive
after_success: make github 

