branches:
  only:
  - master
language: python
addons:
    apt:
        packages:
            - optipng
env:
  global:
  # wradlib.github.io
  - secure: "CHg+j8irEOO3U5eU2Tem6fY9IBbB8loIiWRCVqZeSLUC/ewBaEwGZhSFKkG2da9oXqCXetnl9FOz9icbPNgrjrSj4E2zd2SjK92WWE71F73S5qw1rhCm0eIY99NsamifW5E41QomvQfAnHSQSlE+XNZq1g5kG/cL0aZaBGF7Th4yEmatFAn3/k/+MxYgQu0vlGomR1A85UYU17RTsT11GXPt6rcMMnwKCzFuHvo4nTArhMHosmhACTASUf7L7dOvMQUQI74nzy7/g7KX37oxFfZVNTVXv7+YxD1FsQsGzaGu1xaQIsT/9u3GcFX46/UeN5rroWpvDl7L8PNHhhjOaoDIjQ9HH2jY0KiGWD7O7oo3Bldf+TIkv6Do+HQMtC2zdnjt15yHSrbm0/x841P0651nKNqQFV1YcFQTYPBfIeocs9MJsxBc/Bc02B4Hp1AbPmzezRdFGm8Vjryn9UJnhbVS/l8wllyiDgtc0i/U0a0p4PQQHtNn7A6jb3tsJXuONA8phLzvhhSLXSsl0wzlgXJlHQp/IPilEkTb65p89mwxcamfKymW6e2C9adzHM/5qdn5WZE7IoAlvdxFZBgg2S4vRqZoGNJE+KYrTc9d+IfzXwZEUHYo/it/j1aVW1HwNE3ItybU3Wx53tA49lRyoPAPMbMRtnFtbbQcRrWSKlM="
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always

before_install:
  - git submodule update --init --recursive
after_success: make github 

