branches:
  only:
  - master
language: python
addons:
    apt:
        packages:
            - optipng
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: "G3mkiMEXX/BXHWq7A2+4fUHvoTErn7t+60lL/7djY+cX+20H4/HgSXJoUle+ZjlfkxG/v29CxbuRd7q+InoyUKrTGL35gyqMRHmAPi3pa/p0lSft5hK2VZgdC5+wWsnEy7OEkdW4l+Xd63s0U/J16bO8IY0QkA9pgvYnJWdBV/wCyq8xWeNzK8pyk5HUYv7PM9JHsXsxspQUiEaY/MgzbFG9zL0NRtJN88UVEZvG1+6yTtV2i1XGP/C6tdxvZOsDt7BLtdnsGEOTlL6L0jA5DLdmbIWJKAYPPc7l1zEICIcC5ZTyoz+uYpu2GC6VOgDbe4oAIHU75Yw9Hjz9ZKHmXHfZErauKDhJOfAnIOoNR0P394vhJ9MXZFtGqM4lgKcr5YaCusmZDz1A5M8tHASAI6brt814HWwdbAM1+/hpALwT8zFprRxycSnpcFVPjMIhN0mz5cUnJmmfYAWQh5moUqh7vHJFiDdxu1AbpUzOUawClo2Dr1MUSd5S8XYt4B3jf/gHAoeP9EUb1YIHPIkL01uVu1Qbw69TwXRRAUI+um5Uw7RbqxcTQBDqmsKWPKsnJwudiWCsB1HGyYe9DKXXew7viDj/SDkexXm/djEQksYIxkexuPnA81ICeUSa0s/xYUva7yRn93OBi6PSyRoXc1I0Y3cdjsJGiFV7uykYVW4="
before_install:
  - git submodule update --init --recursive
after_success: make github 

